Add timeout parameter for long running terraform.apply and terraform.destroy
StackStorm-Exchange/stackstorm-terraform pull request #17
Opened 2020-03-19 01:22 UTC by fjudith

This PR adds timeout parameter allowing to the pipeline above 600 seconds ( Stackstorm action timeout default)

## Before 

`terraform.apply` interrupted at 600s

![image](https://user-images.githubusercontent.com/17888379/77021800-0e068b00-6988-11ea-8349-7eefaeb537b4.png)

## After

`terraform.apply` finished successfully

![image](https://user-images.githubusercontent.com/17888379/77021931-7d7c7a80-6988-11ea-931e-d828cc014726.png)

2020-03-21 17:21 UTC, arm4b requested changes
Thanks @fjudith for the contribution!

The change looks good.
The only missing thing: incrementing pack version in https://github.com/StackStorm-Exchange/stackstorm-terraform/blob/master/pack.yaml and adding respective record in Changelog https://github.com/StackStorm-Exchange/stackstorm-terraform/blob/master/CHANGES.md for this fix.

2020-03-21 21:03 UTC, fjudith commented
Done :)

2020-03-21 21:04 UTC, nmaludy approved these changes
LGTM, thanks so much for the contribution!

2020-03-22 00:25 UTC, arm4b approved these changes

2020-03-22 00:26 UTC, merged