update/pass-state-file-to-output
StackStorm-Exchange/stackstorm-terraform pull request #27
Opened 2020-07-21 22:45 UTC by jschoewe

This currently only returns outputs that are defined in the default terraform.tfstate file. Since we name our tfstate files differently we need to pass that filename to retrieve the desired outputs.

2020-07-21 22:56 UTC, jschoewe commented
@nmaludy @kingsleyadam I can't seem to add you as reviewers so I'm just going to link you here

2020-07-21 23:21 UTC, nmaludy requested changes
Please add changelog and bump by 0.0.1 for bug fix

2020-07-21 23:39 UTC, kingsleyadam commented
This definitely seems like a bug/oversite in the python terraform package. If the state path is defined when the terraform object is constructed (which is done here) then it should be used in all methods in the object.

It does seem to be used on the standard, apply, plan, destroy, etc by implementing the method [_generate_default_options](https://github.com/beelit94/python-terraform/blob/master/python_terraform/__init__.py#L118). But does seem to be omitted in the output command.

I'd recommend opening an issue on that project to fix this properly.

If this is merged in, we probably want to also apply this logic to the output [action](https://github.com/StackStorm-Exchange/stackstorm-terraform/blob/master/actions/output.py) which would also need to accept the state path.

2020-07-22 15:07 UTC, jschoewe commented
I opened an issue with the python-terraform project asking if there's a reason why default options aren't being passed to the output method. When I have time I can make a PR for that as well, until then I'd like to get this merged and working and we can update when/if that change happens.

2020-07-22 15:10 UTC, nmaludy approved these changes

2020-07-22 15:17 UTC, merged